# Generated by Django 3.1.2 on 2021-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_mail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
