# Generated by Django 3.1.2 on 2021-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(max_length=500)),
                ('Title2', models.CharField(max_length=500)),
                ('Tag', models.CharField(max_length=900)),
                ('Image', models.ImageField(upload_to='static/sliderImage')),
            ],
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
