# Generated by Django 3.1.2 on 2021-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210207_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidehead',
            name='text1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='slidehead',
            name='text2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sliderimages',
            name='image1',
            field=models.ImageField(default='', upload_to='static/slideImages'),
        ),
        migrations.AddField(
            model_name='sliderimages',
            name='image2',
            field=models.ImageField(default='', upload_to='static/slideImages'),
        ),
        migrations.AddField(
            model_name='slidetag',
            name='text1',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='slidetag',
            name='text2',
            field=models.CharField(default='', max_length=900),
        ),
    ]
