# Generated by Django 3.1.2 on 2021-02-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210207_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidetag',
            old_name='text1',
            new_name='tag1',
        ),
        migrations.RenameField(
            model_name='slidetag',
            old_name='text2',
            new_name='tag2',
        ),
    ]
