# Generated by Django 3.1.2 on 2021-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210207_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='recip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='static/rcp/')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
