# Generated by Django 3.1.2 on 2021-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_recip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recip',
            new_name='recipt',
        ),
    ]
